In [2]:
import numpy as np
import matplotlib.pyplot as plt

# Config the matplotlib backend as plotting inline in IPython
%matplotlib inline

In [ ]:
y=W*x+U*y
Si V=concat(W,U) y z=concat(x,y) se cumple que
y=Vz

In [10]:
def setPreviousY(x,p):
    x[2,:]=p
#Matrix version of linear model
def fm(x):
    y=w*x
    return y
#Initial weights
#            b    w   u
w=np.matrix([5.0,1.2,0.1])
#Data, first row are ones for bias
x=np.matrix([[ 1.0, 1.0, 1.0], #bias data always 1
             [-2.0, 4.5, 6.2], #actual data
             [ 0.0, 0.0, 0.0]])#previous y values
setPreviousY(x,np.matrix([ 0.0, 0.0, 0.0]))
print(x)
y=np.matrix( [ 7.0, 9.0,18.0] )#Matrix version of Gradient descent
#Loss function
def L(w):
    dif=y-fm(x)
    l=dif*dif.T
    return l[0,0]
#Loss gradient is a vector with same dimensions as w
def dL(w):
    p=fm(x) #prediction
    print("p=",p)
    dif=y-p #difference
    print("dif=",dif)
    dL_w=-2*dif*x.T
    #update data but previous only
    setPreviousY(x,p)
    print("x=",x)
    return dL_w
#Learning rate
a=0.01
#Initial weights
#            b    w   u
w=np.matrix([5.0,1.2,0.1])
for i in range(10):
    iw=-dL(w)
    w=w+a*iw
    print("w=",w,"iw=",iw)
print(w)
print(x)

[[ 1.   1.   1. ]
 [-2.   4.5  6.2]
 [ 0.   0.   0. ]]
p= [[  2.6   10.4   12.44]]
dif= [[ 4.4  -1.4   5.56]]
x= [[  1.     1.     1.  ]
 [ -2.     4.5    6.2 ]
 [  2.6   10.4   12.44]]
w= [[ 5.01712   1.238744  0.1     ]] iw= [[ 17.12   38.744  -0.   ]]
p= [[  2.799632   11.631468   13.9413328]]
dif= [[ 4.200368  -2.631468   4.0586672]]
x= [[  1.          1.          1.       ]
 [ -2.          4.5         6.2      ]
 [  2.799632   11.631468   13.9413328]]
w= [[ 5.02837513  1.24858679  0.16808702]] iw= [[ 11.2551344    9.84278928  68.08701914]]
p= [[  3.00178335  12.60211447  15.1129703 ]]
dif= [[ 3.99821665 -3.60211447  2.8870297 ]]
x= [[  1.           1.           1.        ]
 [ -2.           4.5          6.2       ]
 [  3.00178335  12.60211447  15.1129703 ]]
w= [[ 5.0349414   1.23597406  0.18717641]] iw= [[  6.56626375 -12.61272855  19.08939582]]
p= [[  3.12485632  12.95564328  15.52677217]]
dif= [[ 3.87514368 -3.95564328  2.47322783]]
x= [[  1.           1.           1.        ]
 [

In [34]:
#Let treate the matrix data as a sequence colum by colum
#this version doesn't unroll but it seem to work, sure there is some problema

#Matrix version of linear model
def fm(x,w):
    y=w*x
    return y
#Data, first row are ones for bias
x=np.matrix([[ 1.0, 1.0, 1.0], #bias data always 1
             [-2.0, 4.5, 6.2], #actual data
             [ 0.0, 0.0, 0.0]])#previous y values
setPreviousY(x,np.matrix([ 0.0, 0.0, 0.0]))
print(x)
y=np.matrix( [ 7.0, 9.0,18.0] )#Matrix version of Gradient descent
print(y)
#Loss function
def L(w,x,y):
    dif=y-fm(x)
    l=dif*dif.T
    return l[0,0]
#Loss gradient is a vector with same dimensions as w
def dL(w,x,y):
    p=fm(x,w) #prediction
    print("p=",p)
    dif=y-p #difference
    print("dif=",dif)
    dL_w=-2*dif*x.T
    print("x=",x)
    return dL_w,p
#Learning rate
a=0.001
#Initial weights
#            b    w   u
w=np.matrix([5.0,1.2,0.1])
epochs=3
#save data
X=[]
P=np.zeros_like(y)
C=[]
for i in range(epochs):
    print("****** EPOCH",i)
    p=0 #previous y
    for t in range(x.shape[1]):
        xt=x[:,t]
        xt[2,0]=p #update data with previous values
        yt=y[:,t]
        iw,p=dL(w,xt,yt)
        P[0,t]=p
        w=w-a*iw
        print("w=",w,"iw=",iw)
    c=np.sum(np.abs(y-P))/float(x.shape[1])
    print("c=",c)
    C.append(c)
print("++++++++ END")
print(w)
print(x)
print(y)
print(P)
print(C)

[[ 1.   1.   1. ]
 [-2.   4.5  6.2]
 [ 0.   0.   0. ]]
[[  7.   9.  18.]]
****** EPOCH 0
p= [[ 2.6]]
dif= [[ 4.4]]
x= [[ 1.]
 [-2.]
 [ 0.]]
w= [[ 5.0088  1.1824  0.1   ]] iw= [[ -8.8  17.6   0. ]]
p= [[ 10.5896]]
dif= [[-1.5896]]
x= [[ 1. ]
 [ 4.5]
 [ 2.6]]
w= [[ 5.0056208   1.1680936   0.09173408]] iw= [[  3.1792   14.3064    8.26592]]
p= [[ 13.21922833]]
dif= [[ 4.78077167]]
x= [[  1.    ]
 [  6.2   ]
 [ 10.5896]]
w= [[ 5.01518234  1.22737517  0.192987  ]] iw= [[  -9.56154333  -59.28156866 -101.25291928]]
c= 3.59012388881
****** EPOCH 1
p= [[ 2.56043201]]
dif= [[ 4.43956799]]
x= [[ 1.]
 [-2.]
 [ 0.]]
w= [[ 5.02406148  1.2096169   0.192987  ]] iw= [[ -8.87913599  17.75827198   0.        ]]
p= [[ 10.9614676]]
dif= [[-1.9614676]]
x= [[ 1.        ]
 [ 4.5       ]
 [ 2.56043201]]
w= [[ 5.02013854  1.19196369  0.18294259]] iw= [[  3.92293521  17.65320844  10.04440886]]
p= [[ 14.41563269]]
dif= [[ 3.58436731]]
x= [[  1.       ]
 [  6.2      ]
 [ 10.9614676]]
w= [[ 5.02730728  1.23640984  0.

In [1]:
#Lets unroll and then do 
#Matrix version of linear model
def fm(x,w):
    y=w*x
    return y
#Data, first row are ones for bias
x=np.matrix([[ 1.0, 1.0, 1.0], #bias data always 1
             [-2.0, 4.5, 6.2], #actual data
             [ 0.0, 0.0, 0.0]])#previous y values
setPreviousY(x,np.matrix([ 0.0, 0.0, 0.0]))
print(x)
y=np.matrix( [ 7.0, 9.0,18.0] )#Matrix version of Gradient descent
print(y)
#Loss function
def L(w,x,y):
    dif=y-fm(x,w)
    l=dif*dif.T
    return l[0,0]
#Loss gradient is a vector with same dimensions as w
def dL(w,x,y):
    p=fm(x,w) #prediction
    print("p=",p)
    dif=y-p #difference
    print("dif=",dif)
    dL_w=-2*dif*x.T
    print("x=",x)
    return dL_w,p
#Learning rate
a=0.001
#Initial weights
#            b    w   u
w=np.matrix([5.0,1.2,0.1])
epochs=1000
#save data
X=[]
P=np.zeros_like(y)
C=[]
xt,pt={},{}
pt[-1]=np.matrix(np.zeros_like(y[:,0]))
loss=0
for i in range(epochs):
    print("****** EPOCH",i)
    #Forward unroll
    for t in range(x.shape[1]):
        xt[t]=x[:,t]
        xt[t][2,0]=pt[t-1] #update data with previous values (for training is better use actual values of y)
        pt[t]=fm(xt[t],w)
        loss+=L(w,xt[t],y[0,t])
    print("xt=",xt)
    print("pt=",pt)
    for t in reversed(range(x.shape[1])):       
        iw,pt[t]=dL(w,xt[t],yt[t])
        P[0,t]=p
        w=w-a*iw
        print("w=",w,"iw=",iw)
    c=np.sum(np.abs(y-P))/float(x.shape[1])
    print("c=",c)
    C.append(c)
print("++++++++ END")
print(w)
print(x)
print(y)
print(P)
print(C)

NameError: name 'np' is not defined